"""Agregada columna version_software a Fridge

Revision ID: f56ba8e0325b
Revises: 
Create Date: 2026-03-14 17:15:36.550958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56ba8e0325b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_software', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridges', schema=None) as batch_op:
        batch_op.drop_column('version_software')

    # ### end Alembic commands ###
